import Head from "next/head";

const Index = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>
                    Pair of fookin socks
                </h1>
            </main>
        </>
    )
};

export default Index;