name: Build and Deploy

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: GitHub Pages Setup
        uses: actions/configure-pages@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
        
      - name: Install dependencies
        env:
         CI: false
        run: |
          echo "Running 'yarn'"

          yarn
      - name: Build
        env:
         CI: false
        run: |
          echo "Running 'yarn build'"
          yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: windows-latest
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1